apiVersion: v1
kind: Service
metadata:
  name: financial-health-api-service
  labels:
    app: financial-health-api
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # For AWS EKS
    service.beta.kubernetes.io/azure-load-balancer-resource-group: "myResourceGroup"  # For Azure AKS
spec:
  selector:
    app: financial-health-api
  ports:
  - name: http
    protocol: TCP
    port: 80          # External port (what clients connect to)
    targetPort: 5001  # Internal port (your Flask app port)
  type: LoadBalancer
  # Optional: specify load balancer IP (if you have a static IP)
  # loadBalancerIP: "203.0.113.12"
---
# Alternative: NodePort Service (for local clusters like minikube)
apiVersion: v1
kind: Service
metadata:
  name: financial-health-api-nodeport
  labels:
    app: financial-health-api
spec:
  selector:
    app: financial-health-api
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5001
    nodePort: 30080   # External port on each node (30000-32767 range)
  type: NodePort
---
# Alternative: ClusterIP with Ingress (for production with ingress controller)
apiVersion: v1
kind: Service
metadata:
  name: financial-health-api-clusterip
  labels:
    app: financial-health-api
spec:
  selector:
    app: financial-health-api
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5001
  type: ClusterIP
---
# Ingress resource (requires ingress controller like nginx-ingress)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: financial-health-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: financial-health-api.local  # Change to your domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: financial-health-api-clusterip
            port:
              number: 80
