apiVersion: apps/v1
kind: Deployment
metadata:
  name: financial-health-api
  labels:
    app: financial-health-api
spec:
  replicas: 5
  selector:
    matchLabels:
      app: financial-health-api
  template:
    metadata:
      labels:
        app: financial-health-api
    spec:
      containers:
      - name: financial-health-api
        image: financial-health-api:latest
        ports:
        - containerPort: 5001
        env:
        - name: FLASK_ENV
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: financial-health-api-service
  labels:
    app: financial-health-api
spec:
  selector:
    app: financial-health-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5001
  type: LoadBalancer
